name: run main.py

on:
  schedule:
    - cron: '0 8 * * *' # At 08:00 every morning
  workflow_dispatch:

env:
  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Print Secret Values
        run: |
          echo '{{ env.TWILIO_ACCOUNT_SID }}' -n | sha256sum
          echo '{{ env.TWILIO_AUTH_TOKEN }}' -n | sha256sum

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install twilio
          
      - name: execute py script # run main.py
        run: python main.py
